"""added get_recipes method to user model

Revision ID: d63a9feee91b
Revises: 0bdee36bc0e1
Create Date: 2021-02-15 16:08:42.423898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63a9feee91b'
down_revision = '0bdee36bc0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('category', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'category')
    # ### end Alembic commands ###
